config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cdc.osmh-indexer.cmm:
      branch: main
      repo: https://github.com/cessda/cessda.cdc.osmh-indexer.cmm
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cdc.osmh-indexer.cmm git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-viridian-cougar.sh
        container: qc.acc_muggy-smalt-indri
  QC.Doc:
    repos:
      github.com/cessda/cessda.cdc.osmh-indexer.cmm find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-aquamarine-gorilla.sh
        container: qc.doc_wiggy-pear-dingo
      github.com/cessda/cessda.cdc.osmh-indexer.cmm git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-tomato-centipede.sh
        container: qc.doc_clammy-cream-cougar
      github.com/cessda/cessda.cdc.osmh-indexer.cmm markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-salmon-schnauzer.sh
        container: qc.doc_gimpy-green-frigatebird
  QC.Lic:
    repos:
      github.com/cessda/cessda.cdc.osmh-indexer.cmm licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-puce-dugong.sh
        container: qc.lic_flimsy-carmine-booby
  QC.Met:
    repos:
      github.com/cessda/cessda.cdc.osmh-indexer.cmm cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-aqua-ibis.sh
        container: qc.met_skanky-rose-crane
  QC.Sty:
    repos:
      github.com/cessda/cessda.cdc.osmh-indexer.cmm checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-green-peccary.sh
        container: qc.sty_muggy-firebrick-moorhen
      github.com/cessda/cessda.cdc.osmh-indexer.cmm jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-razzmatazz-bullfrog.sh
        container: qc.sty_gimpy-celadon-cheetah
  QC.Ver:
    repos:
      github.com/cessda/cessda.cdc.osmh-indexer.cmm get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-lemon-starfish.sh
        container: qc.ver_trippy-chestnut-malamute
timeout: 5400
